### ISSUE TITLE
Criar um slider com estilo diferente

### ISSUE THREAD

**Issue by lucastonussi** [lucastonussi/site#12]
- [x] Adicionar na página que você está construindo um ou mais sliders

👉 https://www.cssportal.com/style-input-range/

**Comment by lucastonussi** [comment]
Mais exemplos:

- [x] https://vuetifyjs.com/en/components/sliders/

**Comment by marinamq** [comment]
Para criar o slider, eu vou ter que modificar qual arquivo?

**Comment by lucastonussi** [comment]
dentro do marina.vue

**Comment by lucastonussi** [comment]
Uma dica:

https://www.w3schools.com/howto/howto_js_rangeslider.asp

**Comment by lucastonussi** [comment]
Dentro do <template> .... </template>

Você pode colocar isso

```html
<input class="slider" type="range" min="1" max="100" value="50">
```

Ele vai criar um slider range pra vc.

Para estilizar o slide ranger, colocar isso dentro do <style> ... </style> :

```css
.slider {
  width: 100%;
  height: 25px;
  background: #d3d3d3;
  outline: none;
  opacity: 0.7;
}
```
